apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: react-calculator
  namespace: dev
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: react-calculator
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: clusterBuilder
      value: default
  build:
    env:
      - name: BP_NODE_RUN_SCRIPTS
        value: "build"
      - name: BP_WEB_SERVER_ROOT
        value: "build"
  source:
    git:
      url: https://github.com/pivotal-ben-chacko/react-calculator.git 
      ref:
        branch: main
